server:
  port: 8202
  application:
    name: gateway
#日志级别
logging:
  level:
    com:
      wzn:
        ablog:
          admin: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8201/eureka #注册中心地址
  instance:
    prefer-ip-address: true #使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向服务中心注册自定义id
    lease-renewal-interval-in-seconds: 50 #每次发送心跳的时间
#路由配置
spring:
  cloud:
    gateway:
      routes:
        - id: azblog-admin
          #从注册中心拉取请求路径
          uri: lb://azblog-admin
          predicates:
            - Path=/admin/**
          filters:
            - name: RequestRateLimiter
              args:
                #用于限流的键的解析器的 Bean 名字。使用 SpEL表达式取
                key-resolver: '#{@urlKeyResolver}'
                redis-rate-limiter.replenishRate: 15 #令牌桶总容量
                redis-rate-limiter.burstCapacity: 3 #令牌桶每秒填充平均速率
        - id: azblog-article
          uri: lb://azblog-article
          predicates:
            - Path=/article/**,/category/**
        - id: azblog-search
          uri: lb://azblog-search
          predicates:
            - Path=/search/**
  redis:
    host: 192.168.25.136
    port: 6379
  zipkin:
    base-url: http://127.0.0.1:9411
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0 #采样的比例
  main:
    allow-bean-definition-overriding: true
rsakey:
  publicKeyName: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD4qpE7FRL2/7XDh2eGVoqdSIP0MYqZWETWWwW7+rfz7Ngzm+yNKeFiEK34pOvJEDgzcfqNOsL2pb1e0vyKsjFNz9SJU0xLMz8oz1sP+weCT4limJtH60xDPIg3tNdqLSaRhD1swjZEBnuIRanBYn9w0EojA8szCwW+AUgsjnS3twIDAQAB