server:
  port: 8207
spring:
  application:
    name: azblog-article
  datasource:
    url: jdbc:mysql://localhost:3306/a_blogs?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: '0504'
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    open-in-view: true
    show-sql: true